### ISSUE TITLE
Investigate SBT 0.13.13 dependency migration problems

### ISSUE THREAD

**Issue by NicolasRouquette** [JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin#1]
The following are variations due to migrating `dependsOn` for sbt 0.13.13:

[6.5.0 travis build log](https://travis-ci.org/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/builds/176423239)
[6.6.0 travis build log](https://travis-ci.org/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/builds/176434384)
[6.7.0 travis build log](https://travis-ci.org/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/builds/176455691)
[6.8.0 travis build log](https://travis-ci.org/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/builds/176468483)
[6.9.0 travis build log](https://travis-ci.org/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/builds/176478843)
[6.10.0 travis build log](https://travis-ci.org/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/builds/176484464)

Builds 6.[5-7] are variations of this: 
https://github.com/sbt/sbt/issues/2818#issuecomment-261023678

Builds 6.8 and later are based on the [migration doc](http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html#Migrating+when+using+%2C++or)

There is a remaining problem on travis-ci:

The `zipInstall` task should produce two files:

- `/home/travis/build/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/target/bundle1.zip`
- `/home/travis/build/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/target/bundle2.zip`

The log below shows that SBT uploaded the first file; however, the second file isn't there yet.
This suggests that `aetherDeploy` began executing before `zipInstall` completed.

```
...
[info] Uploaded: https://api.bintray.com/content/jpl-imce/gov.nasa.jpl.imce/imce.dynamic_scripts.magicdraw.plugin/6.10.0/gov/nasa/jpl/imce/imce.dynamic_scripts.magicdraw.plugin_2.11/6.10.0/imce.dynamic_scripts.magicdraw.plugin_2.11-6.10.0-part1.zip (250760 KB at 6335.5 KB/sec)
[info] Deployed gov.nasa.jpl.imce:imce.dynamic_scripts.magicdraw.plugin_2.11:zip:part1:6.10.0 to JPL-IMCE (https://api.bintray.com/content/jpl-imce/gov.nasa.jpl.imce/imce.dynamic_scripts.magicdraw.plugin/6.10.0, default, releases+snapshots)
org.eclipse.aether.deployment.DeploymentException: Failed to deploy artifacts: Could not transfer artifact gov.nasa.jpl.imce:imce.dynamic_scripts.magicdraw.plugin_2.11:zip:part2:6.10.0 from/to JPL-IMCE (https://api.bintray.com/content/jpl-imce/gov.nasa.jpl.imce/imce.dynamic_scripts.magicdraw.plugin/6.10.0): /home/travis/build/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/target/bundle2.zip (No such file or directory)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:317)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:245)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:413)
	at aether.AetherPlugin$class.deployIt(Plugin.scala:119)
	at aether.AetherPlugin$.deployIt(Plugin.scala:26)
	at aether.AetherPlugin$$anonfun$deployTask$1.apply(Plugin.scala:68)
	at aether.AetherPlugin$$anonfun$deployTask$1.apply(Plugin.scala:66)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact gov.nasa.jpl.imce:imce.dynamic_scripts.magicdraw.plugin_2.11:zip:part2:6.10.0 from/to JPL-IMCE (https://api.bintray.com/content/jpl-imce/gov.nasa.jpl.imce/imce.dynamic_scripts.magicdraw.plugin/6.10.0): /home/travis/build/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/target/bundle2.zip (No such file or directory)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.put(BasicRepositoryConnector.java:274)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:311)
	... 25 more
Caused by: java.io.FileNotFoundException: /home/travis/build/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/target/bundle2.zip (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.eclipse.aether.spi.connector.transport.PutTask.newInputStream(PutTask.java:56)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.utilPut(AbstractTransporter.java:147)
	at org.eclipse.aether.transport.http.HttpTransporter.access$200(HttpTransporter.java:72)
	at org.eclipse.aether.transport.http.HttpTransporter$PutTaskEntity.writeTo(HttpTransporter.java:579)
	at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:98)
	at org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
	at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:98)
	at org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
	at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:122)
	at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:271)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.sendRequestEntity(ManagedClientConnectionImpl.java:197)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:257)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:715)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:520)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:137)
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:287)
	at org.eclipse.aether.transport.http.HttpTransporter.implPut(HttpTransporter.java:265)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.put(AbstractTransporter.java:117)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.runTask(BasicRepositoryConnector.java:510)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 27 more
org.eclipse.aether.deployment.DeploymentException: Failed to deploy artifacts: Could not transfer artifact gov.nasa.jpl.imce:imce.dynamic_scripts.magicdraw.plugin_2.11:zip:part2:6.10.0 from/to JPL-IMCE (https://api.bintray.com/content/jpl-imce/gov.nasa.jpl.imce/imce.dynamic_scripts.magicdraw.plugin/6.10.0): /home/travis/build/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/target/bundle2.zip (No such file or directory)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:317)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:245)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:413)
	at aether.AetherPlugin$class.deployIt(Plugin.scala:119)
	at aether.AetherPlugin$.deployIt(Plugin.scala:26)
	at aether.AetherPlugin$$anonfun$deployTask$1.apply(Plugin.scala:68)
	at aether.AetherPlugin$$anonfun$deployTask$1.apply(Plugin.scala:66)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact gov.nasa.jpl.imce:imce.dynamic_scripts.magicdraw.plugin_2.11:zip:part2:6.10.0 from/to JPL-IMCE (https://api.bintray.com/content/jpl-imce/gov.nasa.jpl.imce/imce.dynamic_scripts.magicdraw.plugin/6.10.0): /home/travis/build/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/target/bundle2.zip (No such file or directory)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.put(BasicRepositoryConnector.java:274)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:311)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:245)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:413)
	at aether.AetherPlugin$class.deployIt(Plugin.scala:119)
	at aether.AetherPlugin$.deployIt(Plugin.scala:26)
	at aether.AetherPlugin$$anonfun$deployTask$1.apply(Plugin.scala:68)
	at aether.AetherPlugin$$anonfun$deployTask$1.apply(Plugin.scala:66)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /home/travis/build/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/target/bundle2.zip (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.eclipse.aether.spi.connector.transport.PutTask.newInputStream(PutTask.java:56)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.utilPut(AbstractTransporter.java:147)
	at org.eclipse.aether.transport.http.HttpTransporter.access$200(HttpTransporter.java:72)
	at org.eclipse.aether.transport.http.HttpTransporter$PutTaskEntity.writeTo(HttpTransporter.java:579)
	at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:98)
	at org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
	at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:98)
	at org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
	at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:122)
	at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:271)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.sendRequestEntity(ManagedClientConnectionImpl.java:197)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:257)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:715)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:520)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:137)
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:287)
	at org.eclipse.aether.transport.http.HttpTransporter.implPut(HttpTransporter.java:265)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.put(AbstractTransporter.java:117)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.runTask(BasicRepositoryConnector.java:510)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.put(BasicRepositoryConnector.java:274)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:311)
	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:245)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:413)
	at aether.AetherPlugin$class.deployIt(Plugin.scala:119)
	at aether.AetherPlugin$.deployIt(Plugin.scala:26)
	at aether.AetherPlugin$$anonfun$deployTask$1.apply(Plugin.scala:68)
	at aether.AetherPlugin$$anonfun$deployTask$1.apply(Plugin.scala:66)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
	at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:publishSigned) org.eclipse.aether.deployment.DeploymentException: Failed to deploy artifacts: Could not transfer artifact gov.nasa.jpl.imce:imce.dynamic_scripts.magicdraw.plugin_2.11:zip:part2:6.10.0 from/to JPL-IMCE (https://api.bintray.com/content/jpl-imce/gov.nasa.jpl.imce/imce.dynamic_scripts.magicdraw.plugin/6.10.0): /home/travis/build/JPL-IMCE/imce.dynamic_scripts.magicdraw.plugin/target/bundle2.zip (No such file or directory)
[error] Total time: 144 s, completed Nov 16, 2016 7:54:15 PM
```

**Comment by NicolasRouquette** [comment]
It seems that the problem wasn't due to the dependencies but rather to a subtlety that the zip file created on travis-ci was sufficiently compressed to be below the split limit (originally, 250mb) and therefore only produced 1 of the expected 2 parts.

**Comment by NicolasRouquette** [comment]
According to [eed3si9n](https://github.com/eed3si9n)'s [comment](https://github.com/sbt/sbt/issues/2818#issuecomment-261078364), task dependencies should be of the form:

`a := a.dependsOn(b).value`

to force `b` to execute & finish before `a` starts.
